---
openapi: 3.0.0
info:
  title: Solar Inverter Observation API
  description: The endpoints for Solar Inverter reading
  version: 1.0.0-oas3
servers:
- url: https://virtserver.swaggerhub.com/FinEst-Twins/Finest-Platform-Services/1.0.0
paths:
  /viikkisolar/observation:
    post:
      tags:
      - UC03-SolarInverter
      summary: adds observations from solar inverter to UoP
      description: adds observations from solar inverter to UoP
      requestBody:
        description: Observations from Sensors
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InverterReading'
      responses:
        "200":
          description: Data has been forwarded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success_resp'
        "400":
          description: unsuccesful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure_resp'
components:
  schemas:
    InverterReading:
      type: object
      properties:
        name:
          type: string
        timestamp:
          type: string
          format: date-time
        VoltageString1:
          type: number
        CurrentString1:
          type: number
        OutputString1:
          type: integer
        VoltageString2:
          type: number
        CurrentString2:
          type: number
        OutputString2:
          type: integer
        VoltageString3:
          type: number
        CurrentString3:
          type: number
        OutputString3:
          type: integer
        VoltagePhase1:
          type: number
        CurrentPhase1:
          type: number
        OutputPhase1:
          type: integer
        VoltagePhase2:
          type: number
        CurrentPhase2:
          type: number
        OutputPhase2:
          type: integer
        VoltagePhase3:
          type: number
        CurrentPhase3:
          type: number
        OutputPhase3:
          type: integer
        TotalEnergy:
          type: integer
        DailyEnery:
          type: integer
        Status:
          type: integer
        Fault:
          type: integer
    success_resp:
      type: object
      properties:
        status:
          type: string
          example: success
    failure_resp:
      type: object
      properties:
        status:
          type: string
          example: failure
  parameters:
    thing_param:
      name: thing
      in: query
      description: name of the device
      required: true
      style: form
      explode: true
      schema:
        type: string
    minresulttime_param:
      name: minresulttime
      in: query
      description: time at which observation data was received at the data platform
      required: false
      style: form
      explode: true
      schema:
        pattern: YYYY-MM-DDTHH:MM:SS.ff
        type: string
        format: date
    maxresulttime_param:
      name: maxresulttime
      in: query
      description: time at which observation data was received at the data platform
      required: false
      style: form
      explode: true
      schema:
        pattern: YYYY-MM-DDTHH:MM:SS.ff
        type: string
        format: date
    minphenomtime_param:
      name: minphenomtime
      in: query
      description: sampling time recorded and received with observation data
      required: false
      style: form
      explode: true
      schema:
        pattern: YYYY-MM-DDTHH:MM:SS.ff
        type: string
        format: date
    maxphenomtime_param:
      name: maxphenomtime
      in: query
      description: sampling time recorded and received with observation data
      required: false
      style: form
      explode: true
      schema:
        pattern: YYYY-MM-DDTHH:MM:SS.ff
        type: string
        format: date
